### ISSUE TITLE
yopass.se displaying "translations" before every text block

### ISSUE THREAD

**Issue by singletonerik** [jhaals/yopass#1903] opened 2023-10-05 18:32 UTC
Basically, title. Every single block of text has the word "translations:"prepended.

![image](https://github.com/jhaals/yopass/assets/76495693/1f6632f7-93bf-4af9-a480-0940770fe296)

**Comment by saimadib** [comment] 2023-10-09 07:57
How can I reproduce the issue?

**Comment by saimadib** [comment] 2023-10-09 07:58
I think the issue is resolved!

**Comment by singletonerik** [comment] 2023-10-16 21:00
Yes looks fixed now on my end.

**Comment by 24367dfa** [comment] 2024-02-09 08:03
@singletonerik you might consider closing this issue then ;-)

**Closed** 2024-02-12 17:36 UTC
